# Configuration for Client/Service multi process benchmarks

OUTPUT_DIR_NAME="cli-srv_multi_process_multiple_clients"
TOPOLOGIES_DIR="${ROS2_BENCHMARK_SCRIPTS_DIR}/../topologies/cli-srv"
PROFILES_DIR="${ROS2_BENCHMARK_SCRIPTS_DIR}/../profiles"

# Paired topologies
RESULTS=("cli_srv_100kb" "2_cli_srv_100kb" "5_cli_srv_100kb" "10_cli_srv_100kb" "20_cli_srv_100kb")
TOPOLOGIES=("cli_srv_100kb" "2_cli_srv_100kb" "5_cli_srv_100kb" "10_cli_srv_100kb" "20_cli_srv_100kb")

TOPOLOGY1=("cli_100kb" "2_cli_100kb" "5_cli_100kb" "10_cli_100kb" "20_cli_100kb")
TOPOLOGY2=("srv_100kb" "srv_100kb" "srv_100kb" "srv_100kb" "srv_100kb")

# Communication types
RMW_LIST=("fastrtps" "cyclonedds" "zenoh")

# Define COMMS and LOANED_ENV_VARS for each RMW
COMMS_fastrtps=("ipc_off")
COMMS_cyclonedds=("ipc_off")
COMMS_zenoh=("ipc_off")
ZENOH_SESSION_CONFIG_URI=${PROFILES_DIR}/ZENOH_DEFAULT_SESSION_CONFIG.json5