# Configuration for Client/Service benchmarks

OUTPUT_DIR_NAME="actions_single_process_multiple_clients"
TOPOLOGIES=("cli_srv_100kb" "2_cli_srv_100kb" "5_cli_srv_100kb" "10_cli_srv_100kb" "20_cli_srv_100kb")
TOPOLOGIES_DIR="${ROS2_BENCHMARK_SCRIPTS_DIR}/../topologies/actions"

# Define RMWs to iterate over
RMW_LIST=("fastrtps" "cyclonedds")

# Define COMMS and env vars for each RMW
COMMS_fastrtps=("ipc_on" "ipc_off")
COMMS_cyclonedds=("ipc_off")

# COMMS_example=()
