# Configuration for Client/Service benchmarks

OUTPUT_DIR_NAME="cli-srv_single_process_long"
TOPOLOGIES=("cli_srv_architecture")
TOPOLOGIES_DIR="${ROS2_BENCHMARK_SCRIPTS_DIR}/../topologies/cli-srv"

# Define RMWs to iterate over
RMW_LIST=("fastrtps" "cyclonedds" "zenoh")

# Define COMMS and env vars for each RMW
COMMS_fastrtps=("ipc_on" "ipc_off")
COMMS_cyclonedds=("ipc_off")
COMMS_zenoh=("ipc_on" "ipc_off")

# COMMS_example=()
