# Configuration for Pub/Sub benchmarks

OUTPUT_DIR_NAME="pub-sub_single_process_idle"
TOPOLOGIES=("pub_sub_idle")

TOPOLOGIES_DIR="${ROS2_BENCHMARK_SCRIPTS_DIR}/../topologies/pub-sub"
PROFILES_DIR="${ROS2_BENCHMARK_SCRIPTS_DIR}/../profiles"

# Define RMWs to iterate over
RMW_LIST=("fastrtps" "cyclonedds" "zenoh")

# Define COMMS and env vars for each RMW
COMMS_fastrtps=("ipc_on" "ipc_off" "loaned")
LOANED_ENV_VARS_fastrtps=(
    "export FASTRTPS_DEFAULT_PROFILES_FILE=${PROFILES_DIR}/shared_memory_fastdds_preallocated_w_realloc.xml"
    "export RMW_FASTRTPS_USE_QOS_FROM_XML=1"
)

COMMS_cyclonedds=("ipc_off")
LOANED_ENV_VARS_cyclonedds=(
    "export CYCLONEDDS_URI=${PROFILES_DIR}/shared_memory_cyclonedds.xml"
)
COMMS_zenoh=("ipc_on" "ipc_off")
