# Configuration for Client/Service benchmarks

OUTPUT_DIR_NAME="cli-srv_single_process"
TOPOLOGIES=("cli_srv_10b" "cli_srv_100kb" "cli_srv_1mb" "cli_srv_4mb" "10_cli_srv_1mb")
TOPOLOGIES_DIR="${ROS2_BENCHMARK_SCRIPTS_DIR}/../topologies/cli-srv"
PROFILES_DIR="${ROS2_BENCHMARK_SCRIPTS_DIR}/../profiles"

# Define RMWs to iterate over
RMW_LIST=("fastrtps" "cyclonedds" "zenoh")

# Define COMMS and env vars for each RMW
COMMS_fastrtps=("ipc_on" "ipc_off")
COMMS_cyclonedds=("ipc_off")
COMMS_zenoh=("ipc_on" "ipc_off")

# COMMS_example=()
ZENOH_SESSION_CONFIG_URI=${PROFILES_DIR}/ZENOH_DEFAULT_SESSION_CONFIG.json5